# pull official base image
FROM node:lts-alpine as builder

# set working directory
WORKDIR /app

# install app dependencies
COPY package.json .
COPY package-lock.json .

RUN npm install

# add app
COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html
